/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SupplyChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DISTRIBUTORS"
      | "PRODUCERS"
      | "ProductStock"
      | "SELLERS"
      | "SUPPLIERS"
      | "addActor"
      | "addDistributor"
      | "addProducer"
      | "addProduct"
      | "addSeller"
      | "addSupplier"
      | "distributeProduct"
      | "distributorCtr"
      | "listForSale"
      | "markProductSold"
      | "owner"
      | "processProduct"
      | "producerCtr"
      | "productCtr"
      | "sellerCtr"
      | "showStage"
      | "supplierCtr"
      | "supplyProduct"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActorAdded"
      | "ProductAdded"
      | "ProductStageUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DISTRIBUTORS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "PRODUCERS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ProductStock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "SELLERS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "SUPPLIERS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addActor",
    values: [AddressLike, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addDistributor",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addProducer",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addProduct",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addSeller",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addSupplier",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeProduct",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributorCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listForSale",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markProductSold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processProduct",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "producerCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "productCtr",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "sellerCtr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "showStage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supplierCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supplyProduct",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DISTRIBUTORS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PRODUCERS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ProductStock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SELLERS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SUPPLIERS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addActor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addProducer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addProduct", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addSeller", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addSupplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributorCtr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listForSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markProductSold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "producerCtr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "productCtr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sellerCtr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "showStage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supplierCtr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supplyProduct",
    data: BytesLike
  ): Result;
}

export namespace ActorAddedEvent {
  export type InputTuple = [
    actorId: BigNumberish,
    role: BigNumberish,
    actor: AddressLike,
    name: string,
    place: string
  ];
  export type OutputTuple = [
    actorId: bigint,
    role: bigint,
    actor: string,
    name: string,
    place: string
  ];
  export interface OutputObject {
    actorId: bigint;
    role: bigint;
    actor: string;
    name: string;
    place: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductAddedEvent {
  export type InputTuple = [productId: BigNumberish, name: string];
  export type OutputTuple = [productId: bigint, name: string];
  export interface OutputObject {
    productId: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductStageUpdatedEvent {
  export type InputTuple = [productId: BigNumberish, stage: BigNumberish];
  export type OutputTuple = [productId: bigint, stage: bigint];
  export interface OutputObject {
    productId: bigint;
    stage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SupplyChain extends BaseContract {
  connect(runner?: ContractRunner | null): SupplyChain;
  waitForDeployment(): Promise<this>;

  interface: SupplyChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DISTRIBUTORS: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
        role: bigint;
      }
    ],
    "view"
  >;

  PRODUCERS: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
        role: bigint;
      }
    ],
    "view"
  >;

  ProductStock: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint, bigint] & {
        id: bigint;
        name: string;
        description: string;
        supplierId: bigint;
        producerId: bigint;
        distributorId: bigint;
        sellerId: bigint;
        stage: bigint;
      }
    ],
    "view"
  >;

  SELLERS: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
        role: bigint;
      }
    ],
    "view"
  >;

  SUPPLIERS: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
        role: bigint;
      }
    ],
    "view"
  >;

  addActor: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string, _role: BigNumberish],
    [void],
    "nonpayable"
  >;

  addDistributor: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  addProducer: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  addProduct: TypedContractMethod<
    [_name: string, _description: string],
    [void],
    "nonpayable"
  >;

  addSeller: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  addSupplier: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  distributeProduct: TypedContractMethod<
    [_productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  distributorCtr: TypedContractMethod<[], [bigint], "view">;

  listForSale: TypedContractMethod<
    [_productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  markProductSold: TypedContractMethod<
    [_productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  processProduct: TypedContractMethod<
    [_productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  producerCtr: TypedContractMethod<[], [bigint], "view">;

  productCtr: TypedContractMethod<[], [bigint], "view">;

  sellerCtr: TypedContractMethod<[], [bigint], "view">;

  showStage: TypedContractMethod<[_productId: BigNumberish], [string], "view">;

  supplierCtr: TypedContractMethod<[], [bigint], "view">;

  supplyProduct: TypedContractMethod<
    [_productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DISTRIBUTORS"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
        role: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "PRODUCERS"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
        role: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "ProductStock"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint, bigint] & {
        id: bigint;
        name: string;
        description: string;
        supplierId: bigint;
        producerId: bigint;
        distributorId: bigint;
        sellerId: bigint;
        stage: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "SELLERS"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
        role: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "SUPPLIERS"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
        role: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "addActor"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string, _role: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addDistributor"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addProducer"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addProduct"
  ): TypedContractMethod<
    [_name: string, _description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addSeller"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addSupplier"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributeProduct"
  ): TypedContractMethod<[_productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributorCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "listForSale"
  ): TypedContractMethod<[_productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "markProductSold"
  ): TypedContractMethod<[_productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processProduct"
  ): TypedContractMethod<[_productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "producerCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "productCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "sellerCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "showStage"
  ): TypedContractMethod<[_productId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "supplierCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "supplyProduct"
  ): TypedContractMethod<[_productId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "ActorAdded"
  ): TypedContractEvent<
    ActorAddedEvent.InputTuple,
    ActorAddedEvent.OutputTuple,
    ActorAddedEvent.OutputObject
  >;
  getEvent(
    key: "ProductAdded"
  ): TypedContractEvent<
    ProductAddedEvent.InputTuple,
    ProductAddedEvent.OutputTuple,
    ProductAddedEvent.OutputObject
  >;
  getEvent(
    key: "ProductStageUpdated"
  ): TypedContractEvent<
    ProductStageUpdatedEvent.InputTuple,
    ProductStageUpdatedEvent.OutputTuple,
    ProductStageUpdatedEvent.OutputObject
  >;

  filters: {
    "ActorAdded(uint256,uint8,address,string,string)": TypedContractEvent<
      ActorAddedEvent.InputTuple,
      ActorAddedEvent.OutputTuple,
      ActorAddedEvent.OutputObject
    >;
    ActorAdded: TypedContractEvent<
      ActorAddedEvent.InputTuple,
      ActorAddedEvent.OutputTuple,
      ActorAddedEvent.OutputObject
    >;

    "ProductAdded(uint256,string)": TypedContractEvent<
      ProductAddedEvent.InputTuple,
      ProductAddedEvent.OutputTuple,
      ProductAddedEvent.OutputObject
    >;
    ProductAdded: TypedContractEvent<
      ProductAddedEvent.InputTuple,
      ProductAddedEvent.OutputTuple,
      ProductAddedEvent.OutputObject
    >;

    "ProductStageUpdated(uint256,uint8)": TypedContractEvent<
      ProductStageUpdatedEvent.InputTuple,
      ProductStageUpdatedEvent.OutputTuple,
      ProductStageUpdatedEvent.OutputObject
    >;
    ProductStageUpdated: TypedContractEvent<
      ProductStageUpdatedEvent.InputTuple,
      ProductStageUpdatedEvent.OutputTuple,
      ProductStageUpdatedEvent.OutputObject
    >;
  };
}
